//
// Created by alkaratus on 06.02.24.
//
#ifndef RUSSIAN_ROULETTE_SERVER_GAME_PARAMS_H
#define RUSSIAN_ROULETTE_SERVER_GAME_PARAMS_H

const unsigned int ROUND_1_QUESTIONS_NUMBER=12;
const unsigned int ROUND_2_QUESTIONS_NUMBER=10;
const unsigned int ROUND_3_QUESTIONS_NUMBER=8;
const unsigned int ROUND_4_QUESTIONS_NUMBER=6;
const unsigned int ROUND_5_QUESTIONS_NUMBER=4;

#endif //RUSSIAN_ROULETTE_SERVER_GAME_PARAMS_H
